stages:
  build:
    nodeLabel: sbt
    steps:
      - |
        export SDKMAN_DIR="$HOME/.sdkman"
        mkdir -p "${SDKMAN_DIR}/candidates/java/current/bin"
        set +o xtrace
        . "${SDKMAN_DIR}/bin/sdkman-init.sh"
        sdk env install use
        set -o xtrace
        sbt test
        sbt doc
        sbt autoscaling-ecs-draining-lambda/Universal/packageBin
    filesToStash:
      - serverless.yml
      - .nvmrc
      - .sdkmanrc
      - .env
      - target/universal/**
      - deploy.sh
  deployProd:
    nodeLabel: nvm-deployer
    steps:
      - ./deploy.sh
