service: ecs-autoscaling-lifecycle-hooks
useDotenv: true
frameworkVersion: ^3.33.0

provider:
  name: aws
  runtime: java17
  architecture: arm64
  memorySize: 1024
  timeout: 60
  region: us-west-2
  deploymentBucket:
    name: ${env:BUCKET}
    serverSideEncryption: "AES256"
  iam:
    deploymentRole: "arn:aws:iam::${env:ACCOUNT}:role/cloudformation/deployer/cloudformation-deployer"
    role:
      managedPolicies:
        - "arn:aws:iam::aws:policy/service-role/AutoScalingNotificationAccessRole"
      statements:
        - Sid: CorePermissions
          Action:
            - "autoscaling:CompleteLifecycleAction"
            - "ecs:ListClusters"
            - "ecs:ListContainerInstances"
            - "ecs:DescribeContainerInstances"
            - "ecs:UpdateContainerInstancesState"
          Resource: "*"
          Effect: Allow
        - Sid: RepublishMessages
          Effect: Allow
          Resource:
            - Ref: SNSTopicAutoScalingEcsDrainingNotification
          Action:
            - sqs:SendMessage
            - sqs:GetQueueUrl
            - sns:Publish
  tracing:
    lambda: true
  logRetentionInDays: 7
  stackTags:
    Creator: serverless
    Environment: ${self:custom.EnvironmentTag.${opt:stage}}
    Project: ${self:service}
    Team: platform
    Visibility: internal
    "org.label-schema.vcs-ref": ${env:VERSION}
    "org.label-schema.vcs-url": ${env:VCS_URL}

package:
  individually: true

functions:
  TerminationHook:
    handler: com.dwolla.autoscaling.ecs.draining.TerminationEventHandler
    package:
      artifact: ${env:DRAINING_ARTIFACT_PATH}
    events:
      - sns:
          arn:
            Ref: SNSTopicAutoScalingEcsDrainingNotification
          topicName: AutoScalingEcsDrainingNotification

resources:
  Description:
    Auto Scaling Lifecycle Hook that ensures an ECS Container Instance is fully drained before it is terminated by Auto Scaling
  Resources:
    SNSTopicAutoScalingEcsDrainingNotification:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: AutoScalingEcsDrainingNotification
    AllowPublishToSNSTopicAutoScalingEcsDrainingNotification:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                Service: autoscaling.amazonaws.com
              Action:
                - sts:AssumeRole
        Policies:
          - PolicyName: AllowPublishToSNSTopicAutoScalingEcsDrainingNotification
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Resource:
                    - Ref: SNSTopicAutoScalingEcsDrainingNotification
                  Action:
                    - sqs:SendMessage
                    - sqs:GetQueueUrl
                    - sns:Publish

  Outputs:
    SNSTopicAutoScalingEcsDrainingNotification:
      Value:
        Ref: SNSTopicAutoScalingEcsDrainingNotification
      Description:
        Topic used by Auto Scaling to send notifications when instance state is changing
      Export:
        Name: sls-${self:service}-${opt:stage}-SNSTopicAutoScalingEcsDrainingNotification
    AllowPublishToSNSTopicAutoScalingEcsDrainingNotification:
      Value:
        Fn::GetAtt:
          - AllowPublishToSNSTopicAutoScalingEcsDrainingNotification
          - Arn
      Export:
        Name: sls-${self:service}-${opt:stage}-AllowPublishToSNSTopicAutoScalingEcsDrainingNotification
      Description:
        IAM Role to allow Auto Scaling to publish to the SNS Topic for termination lifecycle hooks on ECS instances

custom:
  EnvironmentTag:
    admin: admin
    sandbox: sandbox
